version: '3'

services: 
  ourmarketplace:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'ourmarketplace'
    restart: always
    volumes: 
      - ourmarketplace-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ourmarketplacepguser
      POSTGRES_PASSWORD: ourmarketplacepgpassword

volumes: 
  ourmarketplace-data: